server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: swagqp6068@gmail.com
    password: lehduwchzuhmceuk

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

